# Exercise 3.3. 
## Consider an MDP composed of two states, $\mathcal{S} , \{x, y\}$, and two actions per state, $\mathcal{A} , \{u, m\}$. The possible actions at both states are $u = \text{unmove}$, i.e., to stay in the same state, or $m = \text{move}$ to the other state. The state-transition probabilities are
![img](imgs/Screenshot_2018-04-20_11-23-41.png)
![img](imgs/Screenshot_2018-04-20_11-25-35.png)




In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
#initial parameters
gamma = .9
R = np.matrix([[-1],[.6],[.5],[-.9]])
P = np.matrix([[0.8,0.2],[0.2,0.8],[0.3,0.7],[0.9,0.1]])
pi1 = [[1,0,0,0],[0,0,1,0]]
pi2 = [[0,1,0,0],[0,0,1,0]]
pi3 = [[1,0,0,0],[0,0,0,1]]
pi4 = [[0,1,0,0],[0,0,0,1]]

![img](imgs/Screenshot_2018-05-05_23-55-06.png)

In [2]:
from numpy.linalg import inv

#function to evaluate the state value(V) function of a certain policy
def eval_v(policy):
    P_pi = np.matmul(policy,P)
    R_pi = np.matmul(policy,R)
    
    return np.matmul(inv(np.identity(P_pi.shape[0]) - gamma * P_pi) , R_pi)

#function to evaluate the state-action(Q) value function of a certain policy
def eval_q(policy):
    #product of the transition matrix with the policy
    P_aux = np.matmul(P,policy)
        
    return np.matmul(inv(np.identity(P_aux.shape[0]) - gamma * P_aux) , R)

In [3]:
v1 = eval_v(pi1)
v2 = eval_v(pi2)
v3 = eval_v(pi3)
v4 = eval_v(pi4)
q1 = eval_q(pi1)
q2 = eval_q(pi2)
q3 = eval_q(pi3)
q4 = eval_q(pi4)

![img](imgs/Screenshot_2018-05-05_23-51-30.png)

In [4]:
print('v1 = \n',v1)
print('v2 = \n',v2)
print('v3 = \n',v3)
print('v4 = \n',v4)
print('q1 = \n',q1)
print('q2 = \n',q2)
print('q3 = \n',q3)
print('q4 = \n',q4)

v1 = 
 [[-5.09]
 [-2.36]]
v2 = 
 [[5.34]
 [5.25]]
v3 = 
 [[-9.83]
 [-9.74]]
v4 = 
 [[-0.63]
 [-1.55]]
q1 = 
 [[-5.09]
 [-2.02]
 [-2.36]
 [-5.24]]
q2 = 
 [[3.79]
 [5.34]
 [5.25]
 [3.9 ]]
q3 = 
 [[-9.83]
 [-8.19]
 [-8.29]
 [-9.74]]
q4 = 
 [[-1.73]
 [-0.63]
 [-0.64]
 [-1.55]]
